### ISSUE TITLE
[meta] Fix e2e tests under Spanner

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#201]
To make all the e2e pass on the Spanner backend:

- [x] Fix actix-web's cache holding onto Db connections, exhausting our Db pool

Failing tests:

- [x] test_collection_usage
- [x] test_ifunmodifiedsince 
- [x] test_set_collection_with_if_modified_since 
- [x] test_that_we_dont_resurrect_committed_batches
- [x] test_bulk_update_of_ttls_without_sending_data
- [x] test_delete_storage
- [x] test_get_collection
- [x] test_get_collection_count
- [x] test_get_info_collections
- [x] test_get_item
- [x] test_meta_global_sanity
- [x] test_update_of_ttl_without_sending_data

additionally the following batch tests fail, but let's target these separately as we need to revamp our batch implementation (#173):

- [x] test_batch_id_is_correctly_scoped_to_a_collection
- [x] test_batch_with_immediate_commit 
- [x] test_batch_partial_update 
- [x] test_batch_ttl_is_based_on_commit_timestamp 
- [x] test_batch_ttl_update
- [x] test_batch_uploads_properly_update_info_collections
- [x] test_batches

**Comment by fzzzy** [comment]
All fixed!!!

**Comment by fzzzy** [comment]
Fixed in this branch, that is: https://github.com/mozilla-services/syncstorage-rs/tree/feat/195

**Comment by fzzzy** [comment]
Something seems to have gone wrong with that merge, my changes fixing the end to end tests got lost. They should be in the reflog.

**Comment by fzzzy** [comment]
Lol. The branch just hasn't landed on master yet. feat/195.

**Comment by fzzzy** [comment]
This has landed.
