### ISSUE TITLE
Investigate load testing failures in staging.

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/syncstorage-rs#279]
From @rbillings, the most recent test yielded a large % of errors: `4 hr results: SUCCESSES: 818914 | FAILURES: 24631 | WORKERS: 084`. The test was run today (10/15/19) against v 0.1.2.

Issues affecting the loadtester:

- [x] Bad handling of Accept headers (406 responses) #287
- [x] Exempt dockerflow endpoints from middleware #296
- [x] Lengthen spanner's db pool connection_timeout #302
- [x] Session not found errors sometimes emitted #316 
- [x] Respect remote servers configuration limits [#19](https://github.com/mozilla-services/syncstorage-loadtest/issues/19)
- [x] Improve handling of larger db POOL_MAX_SIZE values under load #330
- [x] Spanner's 20k mutation limit can be triggered by deletes #318
- [ ] Switch to execute_streaming_sql #205
- [ ] Investigate 502 errors during load testing #352

**Comment by pjenvey** [comment]
FYI this earlier loadtest was mistakenly hitting the Python/mysql cluster.

@rbillings ran a new one against the syncstorage-rs cluster, I'll leave this issue open pending its results

**Comment by rbillings** [comment]
I did not actually run any more tests as I was waiting for https://github.com/mozilla-services/syncstorage-rs/pull/281 to be merged. I will run more tests today.

**Comment by pjenvey** [comment]
Issues affecting the loadtester:

- [ ] Bad handling of Accept headers (406 responses) #287

**Comment by tublitzed** [comment]
More detail from @rbillings - latest failed test (today) was run with `SERVER_URL` set to `https://stage.sync.nonprod.cloudops.mozgcp.net/#9c7ba`

**Comment by jrconlin** [comment]
I think we're ok for load testing. @pjenvey noted yesterday that we hit some spanner mutation limits with deletes, but not sure how that will impact the load tests.

**Comment by fzzzy** [comment]
@pjenvey said to wait until the latest version is on stage, hopefully today, and then he will run the load tests first before tapping qa to continue more.

**Comment by tublitzed** [comment]
Currently waiting on the following before trying loadtesting again: 

* [ ] Respect remote servers configuration limits [#19](https://github.com/mozilla-services/syncstorage-loadtest/issues/19)

* ...

**Comment by tublitzed** [comment]
Waiting on [this deploy](https://bugzilla.mozilla.org/show_bug.cgi?id=1597347), then we're going to try again.

**Comment by tublitzed** [comment]
Latest results from @rbillings from a 11/12/19 test: `the first 65min load test results: SUCCESSES: 767552 | FAILURES: 22351 | WORKERS: 005`

**Comment by tublitzed** [comment]
Latest results from a 12/09/19 test: `Almost 4.5 hrs, results look good for the load test: SUCCESSES: 5679667 | FAILURES: 3702 | WORKERS: 009` via @rbillings -
