### ISSUE TITLE
User Migration Meta bug

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#407]
A Meta Bug to cross track all the User Migration issues and PRs.

https://github.com/mozilla-services/tokenserver/issues/159
https://github.com/mozilla-services/syncstorage-rs/pull/401
https://github.com/mozilla-services/server-syncstorage/issues/125
https://github.com/mozilla-services/services-engineering/issues/31
https://github.com/mozilla-services/services-engineering/issues/6

**Comment by jrconlin** [comment]
Additional info from [sync meetup](https://docs.google.com/document/d/1TKLpafQweKbVic4Na3pZl3Mzfgl4WItj32xaWVqPoFg/edit).
- [ ]   Need to [add a second table to syncstorage](https://github.com/mozilla-services/server-syncstorage/pull/136) containing the fxa_uids of migrating users. If id is present, kick back to tokenserver to eventually route to spanner
- [ ]  alter the `migration` table to indicate state of the user migration 
- [ ]  check that user node hasn't changed since start and finish of migration. 
- [ ]  ensure failed user migration ids are logged
- [ ] verify that there are no additional issues around mobile clients.
- [ ] generate fake m/g record for migrated user (before "done") that has new SyncIDs.

**Comment by tublitzed** [comment]
Related [bugzilla link](https://bugzilla.mozilla.org/show_bug.cgi?id=1639645) for migrating the first node. Going to close this out as the migration script portion of this work is done. Will open + link any further refinements needed.
