### ISSUE TITLE
[meta] Create Sync Server Prototype

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/syncstorage-rs#47]
Creating a sync server prototype and retain existing handling and response characteristics with [the existing Python version](https://github.com/mozilla-services/server-syncstorage).

All of these components should behave in a similar compatible manner.

- Request validation/extraction logic
  - [x] [Port default validators](https://github.com/mozilla-services/syncstorage-rs/issues/48)
  - [x] [Port get/delete collection/bso validators](https://github.com/mozilla-services/syncstorage-rs/issues/49)
  - [x] [Port put validators](https://github.com/mozilla-services/syncstorage-rs/issues/50)
  - [x] [Create precondition check middleware](https://github.com/mozilla-services/syncstorage-rs/issues/78)
  - [x] [Port batch validator](https://github.com/mozilla-services/syncstorage-rs/issues/86)
- Error handling for responses
  - [x] [Use failure crate everywhere](https://github.com/mozilla-services/syncstorage-rs/issues/38)
- Logging & Sentry Usage
  - [x] [Add Sentry](https://github.com/mozilla-services/syncstorage-rs/issues/44)
- Database methods (MySQL)
  - [x] [Support a mysql backend](https://github.com/mozilla-services/syncstorage-rs/issues/18)
  - [x] [Create a canonical session timestamp](https://github.com/mozilla-services/syncstorage-rs/issues/55)
  - [x] [Implement batch db calls](https://github.com/mozilla-services/syncstorage-rs/issues/51)
  - [x] [Implement collection-level locking](https://github.com/mozilla-services/syncstorage-rs/issues/52 )
  - [x] [Integrate db layer and handlers w/ a Middleware/Extractor](https://github.com/mozilla-services/syncstorage-rs/issues/65)
- Handler (view) logic to manipulate request data to db calls

**Comment by pjenvey** [comment]
Minus some [e2e test failure issues](https://github.com/mozilla-services/syncstorage-rs/labels/e2e%20tests) we've finished the initial prototype
